#
# Run this file using
#
# $ docker-compose up pre-commit
#
services:
  api:
   build:
     context: .
     target: api
   env_file: apps/api/.env.example
   ports:
     - "3000:3000"

  app:
    build: .
    ports:
    - "5000:80"
  pre-commit:
    build:
      context: .
      dockerfile: pre-commit.dockerfile
    working_dir: /code
    volumes:
    - .:/code
  dev:
    build:
      context: .
      dockerfile: dev.dockerfile
    working_dir: /code
    volumes:
    - .:/code
    ports:
      - "5000:80"
    entrypoint:
    - bash
    - -c
    - |
      corepack install
      pnpm install
      npm run dev
  super-linter:
    image: ghcr.io/super-linter/super-linter:slim-v7.1.0
    environment:
    - RUN_LOCAL=true
    - VALIDATE_MARKDOWN=false
    - VALIDATE_PYTHON_ISORT=false
    - VALIDATE_XML=false
    - VALIDATE_NATURAL_LANGUAGE=false
    - VALIDATE_JSCPD=false
    - IGNORE_GITIGNORED_FILES=true
    - FIX_YAML_PRETTIER=true
    - FIX_CSS=true
    - FIX_JSON=true
    - FIX_JSON_PRETTIER=true
    - FIX_MARKDOWN_PRETTIER=true
    - FIX_TSX=true
    - FIX_TYPESCRIPT_ES=true

    volumes:
    - .:/tmp/lint/
  # This container will run successfully
  # only if all dependencies return no errors.
  test:
    image: busybox
    depends_on:
      pre-commit:
        condition: service_completed_successfully
      super-linter:
        condition: service_completed_successfully
