import { ApiProperty, ApiSchema } from '@nestjs/swagger';
import {
  IsInt,
  IsNumber,
  IsOptional,
  IsString,
  IsUrl,
  Max,
  MaxLength,
  Min,
} from 'class-validator';

@ApiSchema({ name: 'Problem' })
export class GlobalErrorDTO {
  @ApiProperty({
    description: `A short, summary of the problem type. Written in english and readable for engineers (usually not suited for non technical stakeholders and not localized); example: Service Unavailable`,
    type: 'string',
    maxLength: 512,
  })
  @MaxLength(512)
  @IsString()
  title: string;

  @ApiProperty({
    default: 'about:blank',
    description: `An absolute URI that identifies the problem type.  When dereferenced, it SHOULD provide human-readable documentation for the problem type (e.g., using HTML).`,
    example: 'https://tools.ietf.org/html/rfc7231#section-6.6.4',
    format: 'uri',
    type: 'string',
    maxLength: 1024,
    required: false,
  })
  @MaxLength(1024)
  @IsString()
  @IsUrl()
  @IsOptional()
  type?: string;

  @ApiProperty({
    description: `The HTTP status code generated by the origin server for this occurrence of the problem.`,
    example: 503,
    exclusiveMaximum: true,
    format: 'int32',
    maximum: 600,
    minimum: 100,
    type: 'integer',
    required: false,
  })
  @IsNumber()
  @IsOptional()
  @Min(100)
  @Max(600)
  @IsInt()
  status?: number;

  @ApiProperty({
    description: `A human readable explanation specific to this occurrence of the problem. You MUST NOT expose internal informations, personal data or implementation details through this field.`,
    example: 'Request took too long to complete.',
    type: 'string',
    maxLength: 512,
    pattern: '^',
    required: false,
  })
  @MaxLength(512)
  @IsString()
  @IsOptional()
  detail?: string;

  @ApiProperty({
    description: `An absolute URI that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.`,
    format: 'uri',
    type: 'string',
    maxLength: 1024,
    required: false,
  })
  @MaxLength(1024)
  @IsString()
  @IsUrl()
  @IsOptional()
  instance?: string;
}
