SELECT DISTINCT
    ?keyClass (GROUP_CONCAT(?label; separator=" / ") AS ?labels)
WHERE {
  VALUES ?domain { <https://w3id.org/italia/onto/Learning> }

  ?domain <https://w3id.org/italia/onto/ADMS/hasKeyClass> ?keyClass .

  OPTIONAL {
    ?keyClass rdfs:label ?label . FILTER (lang(?label) = 'it')
    }
}

; ---

select distinct * where{

?onto <https://w3id.org/italia/onto/ADMS/hasKeyClass> ?c .

?onto a owl:Ontology .
}

---

SELECT DISTINCT ?subclass ?mid
WHERE {
  VALUES ?rootClass { <https://w3id.org/italia/onto/CPV/Alive> }

  # Get all recursive subclasses with intermediate nodes
  ?rootClass rdfs:subClassOf* ?mid .
  ?mid rdfs:subClassOf ?subclass .

  # Exclude self-references
  #FILTER ( ?subclass != ?mid )
  FILTER( !isBlank(?subclass))
OPTIONAL {
    ?subclass rdfs:label ?label .
    FILTER (lang(?label) = 'it' || lang(?label) = 'en' || lang(?label) = '')
  }
}

---

    PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
    PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

    SELECT DISTINCT
      ?child
      ?parent
    WHERE {
      VALUES ?rootClass { <${classUri}> }

      # Get all recursive superclasses with intermediate nodes
      # excluding self-references and blank nodes
      ?child rdfs:subClassOf* ?rootClass .
      ?child rdfs:subClassOf ?parent .

      FILTER( !isBlank(?child) && !isBlank(?parent) && ?child != ?parent)
    }
