name: Release

on:
  push:
    branches:
      - main
      - next

permissions:
  pull-requests: write
  contents: write
  packages: write
  id-token: write

env:
  CI: true

jobs:
  version:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          # Don't persist credentials to prevent credentials to be leaked on artifacts.
          persist-credentials: false

      - name: Install dependencies
        uses: ./.github/actions/install

      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@6a0a831ff30acef54f2c6aa1cbbc1096b066edaf # v1.7.0
        with:
          version: pnpm ci:version
          publish: pnpm ci:publish
          commit: "chore: update versions"
          title: "chore: update versions"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push tags after publish
        if: steps.changesets.outputs.published == 'true'
        run: git push --follow-tags
